$(function(){
	$('#nav').on({
	click:function(){
		// console.log($(this).text())
		if($(this).text()=='首页'){
	        $('#content').load('./pages/shouye.html');
			}
		if($(this).text()=='商家管理'){
	        $('#content').load('./pages/bussiness.html');
			}
		if($(this).text()=='招聘管理'){
			$('#content').load('./pages/employment.html');
			}
		if($(this).text()=='用户管理'){
			$('#content').load('./pages/jobhunter.html');
			}
		if($(this).text()=='模块管理'){
			$('#content').load('./pages/model.html');
			}
		if($(this).text()=='客服管理'){
			$('#content').load('./pages/customer-service.html');
			}
		if($(this).text()=='审核模块'){
			$('#content').load('./pages/audits.html');
			}
		if($(this).text()=='求职联系'){
			$('#content').load('./pages/employ-jobhunter.html');
			}
	}
	},'span')
})